# account_id = ""
name = "cf-worker-status-page-typescript"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-typescript
kv_namespaces = [ { binding = "KV_STORE", id = "f2e1bb2e72db49dab3020ba686faf442" }, ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[observability]
enabled = true
head_sampling_rate = 0.1 # 10% of requests are logged

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "f2e1bb2e72db49dab3020ba686faf442" }, ]

[env.production.triggers]
crons = [
  # https://crontab.guru/#*/2_*_*_*_*
  # Check monitors
  "*/30 * * * *",
  # https://crontab.guru/#*/10_*_*_*_*
  # Update remote csv monitors
  #"*/10 * * * *",
]
