name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  # Force all Node.js actions to use Node.js 24 (Node.js 20 actions are deprecated)
  # See: https://github.blog/changelog/2025-09-19-deprecation-of-node-20-on-github-actions-runners/
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: pnpm/action-setup@v5
        name: Install pnpm
        with:
          version: latest #10
          run_install: |
            - recursive: true
              args: [--force, --fix-lockfile, --no-frozen-lockfile]

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.12'

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          secrets: |
            SECRET_DISCORD_WEBHOOK_URL
        env:
          SECRET_DISCORD_WEBHOOK_URL: ${{ secrets.SECRET_DISCORD_WEBHOOK_URL }}

      - uses: actions/upload-artifact@v7
        with:
          name: build
          path: |
            ~/**/pnpm-lock.yaml
            ~/**/worker-configuration.d.ts
