name: Deploy

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: latest #10
          run_install: |
            - recursive: true
              args: [--force, --fix-lockfile]

      - name: Build
        run: pnpm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: pnpm
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          environment: production
          secrets: |
            SECRET_DISCORD_WEBHOOK_URL
        env:
          SECRET_DISCORD_WEBHOOK_URL: ${{ secrets.SECRET_DISCORD_WEBHOOK_URL }}

      - uses: actions/upload-artifact@v4
        with:
          name: pnpm-lock
          path: |
            ~/**/pnpm-lock.yaml
